"""update message table

Revision ID: 6ae793dc23d1
Revises: 6d7b042b9eca
Create Date: 2023-05-25 20:46:01.771790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae793dc23d1'
down_revision = '6d7b042b9eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_recipient_id_fkey', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('messages_recipient_id_fkey', 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###
