"""update lesson

Revision ID: f4f11e1f5b92
Revises: af649411773c
Create Date: 2023-05-21 07:51:44.017287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f11e1f5b92'
down_revision = 'af649411773c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=100), nullable=False))
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
